remove propaganda
irchelp/irchelp.github.io pull request #31
Opened 2022-12-18 16:57 UTC by kangarooo

Rusnet problem description
  slocation: Russia, Ukraine, Latvia, USA
  information: >
    RusNet serves the Russian-speaking community with servers spread throughout the former Soviet Union and a few more outside it.
=== Rationale for removal === Rusnet description was not regional but imperialistic- mentioning occupied countries as collaborators.
They were never soviet union countries, but occupied, like whole Russia is before Soviet union multiple occupied countries. This is propaganda that USA, Latvia and Ukraine are post soviet, maybe Russia is post soviet, to act that they have nothing to do with people they left in other occupied territories, so they wont have country to be deported of and wont have existing country passport. USA were not even close but others- They were occupied and were not post-soviet occupation, they were before occupation. Calling something that was made is a complete delusion of history propaganda from USSR Russia lies. Also theese irc servers are not checked with bot if are up at all, so i checked and they are all down. If some works- cant be used for propaganda purposes. === Additional- war ===
Because of Russia war trying to occupy Ukraine most Russian servers are blocked. Especially for propaganda purposes.

2022-12-18 19:13 UTC, a-raccoon commented
I'm not smart or anything, I just know I have family from 2 generations ago that were Ukrainian, who occupied Berlin as soldiers of the USSR in the late 1940s to the early 1950s.  I don't know why they wore soviet uniforms, but their homes and family were in Ukraine.

2022-12-18 20:22 UTC, bw1 commented
```
21:14 -!- irc.lucky.net irc.lucky.net 0 LuckyNet/Kyiv RusNet IRC server
21:14 -!- irc.meganet.ru irc.lucky.net 1 Meganet RusNet Server
21:14 -!- irc.run.net irc.meganet.ru 2 Saint-Petersburg server of RusNet IRC
21:14 -!- *.RusNet irc.run.net 3 Services for RusNet IRC Network
21:14 -!- irc.tomsk.net irc.run.net 3 Tomsk IRC Server, RusNet IRC network
21:14 -!- irc.intertax.ru irc.tomsk.net 4 Intertax RusNet IRC server  (Krasnoyarsk, Siberia)
21:14 -!- irc.anarxi.st irc.run.net 3 [176.105.254.200] anarxi.st Italy (BREEZLE LLC), RusNet IRC
21:14 -!- irc.tambov.ru irc.meganet.ru 2 [195.19.116.14] Tambov RusNet Server
21:14 -!- irc.tom.ru irc.tomsk.net 4 [93.170.100.205] Tomsk Academ IRC Server
21:14 -!- * End of LINKS list.
```

```
21:20 -!- There are 343 users and 0 services on 9 servers
21:20 -!- 9 operators online
21:20 -!- 4768 unknown connections
21:20 -!- 456 channels formed
21:20 -!- I have 50 users, 0 services and 1 servers
21:20 -!- Current local users: 50  Max: 180
21:20 -!- Current global users: 343  Max: 854
```

2022-12-20 04:27 UTC, kangarooo commented
> I'm not smart or anything, I just know I have family from 2 generations ago that were Ukrainian, who occupied Berlin as soldiers of the USSR in the late 1940s to the early 1950s. I don't know why they wore soviet uniforms, but their homes and family were in Ukraine and they were called Ukrainian.

Well people wanted to stop one evil, who was made by sencond evil to occupy lands and to do that- made Hitler
Now to do that they made conspiracy that wont attack- just will occuppy half.
Now still Russia lies- when freed while raping they acted that saving 4 million jews in war time while communists before war killed 8 million Ukrainians in Golodomor, raped in war, in war killed 2x more then hitler.

> Is Texas a Yankee-occupied Confederate State, or a United State of America, or a territory of Mexico?
Are you suggesting that we infiltrate russian irc server to steal Crimea? Moskov was Ukraine territorry, Russia was made later and then stole it too, like trying to steal Crimea.
Here nazis that came in Ukraine from Russia in 2014 in Donbass that Russia claims comming to "Free Kiev" bombing it over Donbas in different place from even if they were in Donbass. Its just lies. 
https://www.youtube.com/watch?v=SEX6JAXunf0


Your edited addition politicizing war propaganda irc channel official description to keep with this Mexico argument that i dont know about and is out of context, since nothing to do with soviet union, showed your values not only why you wanted to keep this propaganda but also why you talk about some other country and possibly giving reason to keep that thing also to be fixed. Just because one problem isntf fixed doesnt mean we should allow again some new to happen so here in code we just remove it.

2022-12-20 20:45 UTC, a-raccoon commented
I don't care enough about this to care.  I just don't feel like approving edits by someone who wants to introduce politics into how an IRC network advertises itself.  Nobody reading our website cares either, except for you.  Everyone understand that anything printed on the Internet has to be read with "bring your own judgement."

2022-12-20 20:52 UTC, a-raccoon requested changes
Vandalism. This commit will not be merged because it proposes to erase real and true information based on an individuals personal biases and political interests.  Further vandalism will result in a ban.

2022-12-21 00:31 UTC, kangarooo commented
fake info and propaganda irc channels should be removed. where else to report this?

2022-12-21 03:10 UTC, a-raccoon commented
> fake info and propaganda irc channels should be removed.

No, they shouldn't.  This website isn't some pre-Musk Twitter where writings are policed based on the current-thing pop cultural correctness.  You're not even challenging any sort of written propoganda, but the very existence of an IRC network, that does in fact exist, but you want to make sure that nobody else is allowed to access it.  A real arbiter of truth soldier.

2022-12-24 14:53 UTC, closed without merging